### PR TITLE
#208

### PR DESCRIPTION
**Pull request by balmas**
add missing form to greek pronoun table

### CODE REVIEW

**Comment by balmas** [comment]
data only change. merging without review.

**Comment by irina060981** [comment]
@balmas, after these changes the result for the following PR is other
https://github.com/alpheios-project/alpheios-core/pull/308

and now `ἀττα` has an inflection table
image

And this fact broke my test from that PR
That's why now travis testing fails for later Pull Requests

I am not sure - was that test really correct? should this word has some inflection tables for Pronoun or not?

**Comment by balmas** [comment]
that's interesting. I think the change in the test behavior is correct - i.e. the reason we couldn't determine a pronoun class for ἀττα before was that we couldn't find the inflected form that the parser reports for it (ἄσσα) in the pronoun table data. Now that the form is there, we can find the class and produce the table.  So the code change you made for #308 is still a desired change, but the test for it should use a different word (or we could make one up I guess) .

Sorry for not catching that it broke the test!!

**Comment by irina060981** [comment]
Ok, I will use this for the test :)
image

**Pull request merged**
