### PR TITLE
Fix tokenization adapter - availability error

### PR DESCRIPTION
**Pull request by irina060981**
For issues https://github.com/alpheios-project/alignment-editor-new/issues/50 and https://github.com/alpheios-project/alignment-editor-new/issues/54
- commented availability check for the tokenization service - we need to get availability langs first (skipped one unit test)
- added availability error to ClientAdapters initialization - tokenization service (would be published to Notification bar)

image

### CODE REVIEW

**Comment by irina060981** [comment]
@balmas , I turned this check for available languages by default - but here I don't know what languages could be used.
And how tokenization servie is working? 
I believe it doesn't check the languages but fails for non cirillic characters?

**Comment by irina060981** [comment]
@balmas, I would merge it without approval - there are small changes to fix the bug.
Tests are well (besides one lexicon test because of network traffic)

**Comment by balmas** [comment]
> @balmas , I turned off this check for available languages.
> I don't know what languages could be used.
> And how tokenization servie is working?
> I believe it doesn't check the languages but fails for non cirillic characters?

The current explicitly supported languages can be found in https://github.com/alpheios-project/tokenizer/blob/master/tokenizer/lib/spacy/lang/mapper.py

If it's not one of those it will default to a generic multilanguage model

**Comment by irina060981** [comment]
then there is no need in available languages check, I believe

**Comment by balmas** [comment]
> then there is no need in available languages check, I believe

I agree.

**Pull request merged**
