### PR TITLE
Move options to data models

### PR DESCRIPTION
**Pull request by irina060981**
This is the first step for adding settings to alpheios-alignment-editor.
I moved Options, Option-Item and all storage classes to data-models (without any code updates),
also moved unit tests.
Updated build for `data-models` to include in embeded-lib.

Related PR 
https://github.com/alpheios-project/webextension/pull/313
https://github.com/alpheios-project/embed-lib/pull/123

### CODE REVIEW

**Review by kirlat — APPROVED** [review]
Looks good!

**Review by balmas — APPROVED** [review]

**Review by balmas — COMMENTED** [review]
we're going to have to add an npm package for data models though

**Review by balmas — CHANGES_REQUESTED** [review]
actually, I think we need to add options to components plugins.js to expose it that way, like we do for Logger and L10n:

```
import { Logger } from 'alpheios-data-models'
import { L10n } from 'alpheios-l10n'

export {
  Popup, Panel, L10n, Locales, enUS, enGB, AppController, UIEventController,
  Language, HTMLSelector, LexicalQuery, ResourceQuery,
  LocalStorageArea, ExtensionSyncStorage, FeatureOptionDefaults, LanguageOptionDefaults, UIOptionDefaults,
  DefaultsLoader, Options, UIStateAPI, Style, HTMLConsole, MouseDblClick, LongTap, Swipe, GenericEvt, AlignmentSelector,
  HTMLPage, Tab, TabScript, L10nModule, AuthModule, PanelModule, PopupModule, ToolbarModule,
  ActionPanelModule, Platform, AuthData, SessionAuthenticator, AppAuthenticator, Logger
}
```

@kirlat do you agree?

**Comment by kirlat** [comment]
> actually, I think we need to add options to components plugins.js to expose it that way, like we do for Logger and L10n:
> 
> ```
> import { Logger } from 'alpheios-data-models'
> import { L10n } from 'alpheios-l10n'
> 
> export {
>   Popup, Panel, L10n, Locales, enUS, enGB, AppController, UIEventController,
>   Language, HTMLSelector, LexicalQuery, ResourceQuery,
>   LocalStorageArea, ExtensionSyncStorage, FeatureOptionDefaults, LanguageOptionDefaults, UIOptionDefaults,
>   DefaultsLoader, Options, UIStateAPI, Style, HTMLConsole, MouseDblClick, LongTap, Swipe, GenericEvt, AlignmentSelector,
>   HTMLPage, Tab, TabScript, L10nModule, AuthModule, PanelModule, PopupModule, ToolbarModule,
>   ActionPanelModule, Platform, AuthData, SessionAuthenticator, AppAuthenticator, Logger
> }
> ```
> 
> @kirlat do you agree?

Yes, I think it's the way to go

**Comment by irina060981** [comment]
I could explain why I didn't choose to go this way.
If we would always import only `alpheios-components` and use `alpheios-core` as a single package we could import all classes only through `alpheios-components`.
If I would need to import classes separately I could import from all besides `alpheios-components`.
That's why to avoid this limitation I decided not to mix classes imports.

But if you both consider that it is not necessary let's do as you decided.
I don't need to import `alpheios-components` to my `alpheios-alignment-editor`, so it won't prevent me to go further with developing.

**Comment by irina060981** [comment]
ok, I think I could merge now

**Pull request merged**
